### ISSUE TITLE
Use LDAP bind instead of check_password

### ISSUE THREAD

**Issue by vauxia** [nitmir/django-cas-server#18]
A common pattern for LDAP authentication is to bind against the LDAP server using the target user's DN and password, which means you'd never need to see/use/compare the userPassword attribute at all.  As such, my LDAP ACLs make it such that userPassword is never returned by LDAP, in any form.

The CAS LDAP implementation uses check_password(), which requires the LDAP server to return userPassword so that it can be compared with the POSTed value. I would prefer to bind against the server with the user's credentials, instead.

**Comment by vauxia** [comment]
I implemented LDAP search/bind at https://github.com/vauxia/django-cas-server . Authentication now works correctly using an LDAP re-bind, but something is still not working.

LdapAuthUser did not implement the attributs method to return attributes. I added an attributs method, but I wasn't sure how best to format a return value. It seems that these are being managed inconsistently.

After a night's sleep, I realized that I should use DjangoAuthUser after all: my users are stored in LDAP, but I will probably have attributes and metadata that only Django knows about. I will work on using LDAP as a backend for Django auth proper, and I will use DjangoAuthUser for CAS.

My fork provides a useful feature, but I will probably not do more work on the LdapAuthUser method.

**Comment by nitmir** [comment]
The attributes methods always return a dictionary with attributes name as key and attribute value or list of attribute value as values (if the list only as 1 element, it is managed the same way as if the value was that single element). (cf https://django-cas-server.readthedocs.io/en/latest/package/cas_server.auth.html#cas_server.auth.DBAuthUser.attributs)

I  think that directly bind as the user on ldap do not allow to retrieve the user attribute each time he/she ask for a ticket generation (unless we start storing the user credential for bind to the ldap backend when needed, but I prefer not to do that, or we store the user attribute on login, we may use the FederatedUser model for that, but it means than the user attributes transmitted to a service may be outdated).

It's fairly common to use bind to ldap as a readonly admin to allow attribute retrieval. Normally, the user attribute userPassword is hashed and salted (e.g. with the {SSHA} scheme) so it's an opaque value, and we get the user password anyway as he/she posted it.

If you think it is still interesting to have an auth class that directly bind as the user, I may try to implement it but as a different class than LdapAuthUser (LdapAuthBindUser maybe ?).

**Comment by nitmir** [comment]
Ok, I had a look at https://github.com/vauxia/django-cas-server/commit/d3e7328348cf91cf399a54061581b4b355bac58a . You still use a global connection for retrieving user dn (may be an anonymous one ?) and attributes, and just bind as the user for checking password. I may be a good compromise: If you do not need user attributes, bind anonymously just to get the dn, else use an ro admin bind.

Maybe you should add a value to CAS_LDAP_PASSWORD_CHECK (like "bind") instead of the CAS_LDAP_BIND parameter.

**Comment by vauxia** [comment]
The search/bind implementation is the only kind of implementation I've ever seen in LDAP authentication libraries. You don't want your LDAP server to be able to return userPassword -- anonymously, or to a specific user.

It may also be good to collect attributes as the user. My search/auth user can only access the dn, uid, mail attributes. "self" is likely to have more access to more attributes.

I think it's a good idea to use "bind" for accounts.advantagelabs.com instead of adding CAS_LDAP_BIND.
