### ISSUE TITLE
Service xx not allowed

### ISSUE THREAD

**Issue by SolarisYan** [nitmir/django-cas-server#2]
i want to use the cas-server as an alone server,and other django app as the cas client.i use the django-cas-ng ,but when i login,only login page show,and don't redirect to the url that i want.

Service http://xx:8000/accounts/login/?next=%2Fconsole%2F non allowed.

Log In Successful
You have successfully logged into the Central Authentication Service.
For security reasons, please Log Out and Exit your web browser when you are done accessing services that require authentication!

can you help me? thank you

**Comment by nitmir** [comment]
Did you add a pattern for "Service xx" in django admin ? (`/admin/cas_server/servicepattern/`)

**Comment by nitmir** [comment]
Any update ?
