### ISSUE TITLE
Salt option for passwords

### ISSUE THREAD

**Issue by Xqua** [nitmir/django-cas-server#29]
I can't seem to find any option to add salt on password hash for MD5 SHA512 or other hash (except Crypt)

Am I missing something ?

**Comment by nitmir** [comment]
There is none.
Direct hash are just here to give some authentication class examples.
You should write you own authentication class implementing https://github.com/nitmir/django-cas-server/blob/master/cas_server/auth.py#L37

You can always subclass `SqlAuthUser` or `LdapAuthUser` (I do not known which one you are using) and just change the `test_password` method to suit your case.

I do not intend to add salt options for plain hash algorithms as some people may hash differently (with the salt before or after for exemple) with the salt stored differently (in another field, on the first bytes of the password hash, with a separator in the password hash, ...). Contrary to the the [crypt](https://en.wikipedia.org/wiki/Crypt_(C)) format which is well documented.
