### ISSUE TITLE
Unknown field last_update on FederateUserAdmin

### ISSUE THREAD

**Issue by denrique88** [nitmir/django-cas-server#30]
When I go to Admin > Central Authentication Service > Federated users and that I want to add a federated user, I've an error saying that last_update field is unknown.

I could resolve the problem by erasing last_update in Class FederatedUserAdmin (admin.py) but that's maybe not the best solution.

**Comment by nitmir** [comment]
You are not suppose to manually create any user (federated users or normal user). There are automatically created upon authentication and deleted then the user is no more authenticated anywhere.

**Comment by nitmir** [comment]
I close this for now, do not hesitate to reopen it if you are still facing this issue.
