### ISSUE TITLE
Problems with federated provider

### ISSUE THREAD

**Issue by denrique88** [nitmir/django-cas-server#31]
Hello,

I don't know where to post to have a little bit help in using the federated mode in django-cas-server.

I would like to use django-cas-server as a CAS consumer and CAS provider : django-cas-server would ask a CAS server to authenticate, then the CAS server send the user login and attributes to django-cas-server and django-cas-server can be used as a CAS server by other applications.

If I read corretly the documentation, that seems possible.

But presently, I have set the identity provider : one of my CAS server (LemonLDAP). When I try to log in via django-cas-server to the CAS server (OpenLDAP), it's ok. But then, I'm not redirected to django, the CAS server redirects me to his portal. So I don't know if dajango-cas-server really got the user and its attributes.

Could someone help me, please ?

**Comment by nitmir** [comment]
A CAS server is suppose to redirect you to the URL in the `service=` parameter you give to the CAS server and appending to it a `ticker=ST-…` parameter (upon successful authentication).

Here a exemple with a jasig CAS as backend. Only parameters set in settings.py are `LOGIN` ([to the file](https://django-cas-server.readthedocs.io/en/latest/README.html#logs) /tmp/cas_server.log) and [`CAS_FEDERATE=True`](https://django-cas-server.readthedocs.io/en/latest/README.html#federation-mode). The CAS provider was added using django admin.

1. select the provider and click Connect
![service central d authentification - mozilla firefox_016](https://user-images.githubusercontent.com/5030463/28769730-f14e6bf0-75dc-11e7-86ea-c3db8369c8b6.png)

2. You are redirected to the provider CAS
![service d authentification de l ens de cachan - mozilla firefox_017](https://user-images.githubusercontent.com/5030463/28769800-3d09ab7c-75dd-11e7-80df-e7e59a996996.png)

3. Upon successful authentication, you are redirected to django-cas-server, and your are authenticated.
![service central d authentification - mozilla firefox_018](https://user-images.githubusercontent.com/5030463/28769819-4ebdd23a-75dd-11e7-8a56-6f8b24eb52cc.png)

The HTTP logs looks like (here from the django dev server, but logs from apache2 (`/var/log/apache2/access.log`) or nginx (`/var/log/nginx/access.log`) or any web server are similar):
```
[31/Jul/2017 08:39:42] "GET /login HTTP/1.1" 200 4125
[31/Jul/2017 08:39:42] "GET /static/cas_server/styles.css HTTP/1.1" 304 0
[31/Jul/2017 08:39:42] "GET /static/cas_server/functions.js HTTP/1.1" 304 0
[31/Jul/2017 08:39:42] "GET /static/cas_server/logo.png HTTP/1.1" 304 0
[31/Jul/2017 08:40:00] "POST /federate HTTP/1.1" 302 0
[31/Jul/2017 08:40:00] "GET /federate/ens-cachan.fr HTTP/1.1" 302 0
[31/Jul/2017 08:40:38] "GET /federate/ens-cachan.fr?ticket=ST-164793-MsWQZbLToX5Skw9hNuwQ-cas.ens-cachan.fr HTTP/1.1" 302 0
[31/Jul/2017 08:40:39] "GET /login HTTP/1.1" 200 3749
[31/Jul/2017 08:40:39] "POST /login HTTP/1.1" 200 3048
```

At `[31/Jul/2017 08:40:00] "GET /federate/ens-cachan.fr HTTP/1.1" 302 0` I am redirected to the provider CAS. At `[31/Jul/2017 08:40:38] "GET /federate/ens-cachan.fr?ticket=ST-164793-MsWQZbLToX5Skw9hNuwQ-cas.ens-cachan.fr HTTP/1.1" 302 0` the provider CAS redirect to django CAS appending the `ticket=` parameter.

The django CAS logs (setup with the `LOGIN` parameter in settings.py to log to /tmp/cas_server.log) looks like:
```
2017-07-31 08:40:00,445 INFO Trying to authenticate https://cas.ens-cachan.fr/ again
2017-07-31 08:40:38,927 INFO Got a valid ticket for vsamir from https://cas.ens-cachan.fr/
2017-07-31 08:40:39,418 INFO User vsamir@ens-cachan.fr successfully authenticated
```

Please provide some logs (http logs and django-cas-server logs) so I can see what's happening to you.

**Comment by nitmir** [comment]
I close this for now, do not hesitate to reopen it, providing logs, if you are still facing this issue.
