### ISSUE TITLE
LC_MESSAGE PT_BR

### ISSUE THREAD

**Issue by robertomorati** [nitmir/django-cas-server#32]

**Comment by nitmir** [comment]
uh yes ?

**Comment by robertomorati** [comment]
Hi @nitmir,

Sorry for the delay to write something here.
I translated the po file to portuguese.

**Comment by robertomorati** [comment]
@nitmir is it possible add the file to support portuguese?
Thanks
[pt_BR.zip](https://github.com/nitmir/django-cas-server/files/1242142/pt_BR.zip)

**Comment by robertomorati** [comment]
@vauxia @nitmir,

Is it possible add the file to support portuguese, please?

Thanks
[pt_BR.zip](https://github.com/nitmir/django-cas-server/files/1248592/pt_BR.zip)

**Comment by nitmir** [comment]
Done in f1a47e77660f13797ad6e1694c56472be97a59b5

This will be in the next release

**Comment by robertomorati** [comment]
Hi @nitmir,

Was make  django-admin compilemessages?
Because, I didn't do that... Sorry!

Thanks
Have a nice week,
