### ISSUE TITLE
Use Federate and classic mode.

### ISSUE THREAD

**Issue by nicotsch** [nitmir/django-cas-server#36]
I search how I can use federate and classic login process on different url or subdomains.
It's possible?

I have try to change the CAS_FEDERATE settings values according to the subdomains. It seems to work but it's not clean.

Thank
P.S: Sorry for my bad English

**Comment by nitmir** [comment]
It is actually not intended to work both in federated and non federated mode.
If you need both, the easiest way is to run two django instances, one in federated mode and the other in normal mode.

**Comment by nicotsch** [comment]
ok. Thank for reply. That's what I did!
