### ISSUE TITLE
Empty attributs part in serviceValidate request response

### ISSUE THREAD

**Issue by davis90** [nitmir/django-cas-server#37]
Hello,

I try to manage user attributes, but I always have an empty data when I receive response from serviceValidate.

this is some settings I use for the django cas server:

```
CAS_AUTH_CLASS = 'cas_server.auth.SqlAuthUser'
CAS_SQL_PASSWORD_CHECK = "plain"
CAS_SQL_USER_QUERY = "SELECT username, password, cas_users.* FROM cas_users WHERE username = %s"
```

When I try to connect to the CAS server with flask CAS, i have this error:

> TypeError
> TypeError: argument of type 'NoneType' is not iterable
> 
> ....
> File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "/usr/local/lib/python2.7/dist-packages/Flask_CAS-1.0.1-py2.7.egg/flask_cas/routing.py", line 45, in login
> if validate(flask.session[cas_token_session_key]):
> File "/usr/local/lib/python2.7/dist-packages/Flask_CAS-1.0.1-py2.7.egg/flask_cas/routing.py", line 127, in validate
> if "cas:memberOf" in attributes:

This this the content of the serviceValidate response:

> \<cas:serviceResponse xmlns:cas="http://www.yale.edu/tp/cas">
> \<cas:authenticationSuccess>
> \<cas:user>test1</cas:user>
> \<cas:attributes></cas:attributes>
> \</cas:authenticationSuccess>
> </cas:serviceResponse>

Because of <cas:attributes> is empty, flask-CAS make an error. I Tried to remove attributes part or add one , but I failed, How can I do?

Many thanks in advance for your assistance,

**Comment by nitmir** [comment]
ff8373ee6a00fe8664d1771277a0ae7099c49081 should fix this as the attributes list can no longer be empty
