### ISSUE TITLE
Password hashes with LDAP + {CRYPT} fail on DES encoding

### ISSUE THREAD

**Issue by tobast** [nitmir/django-cas-server#53]
When authenticating against LDAP with `ldap` password check type, the authentication will fail with Error 500 if the password is encrypted using (deprecated and insecure) DES method.

# Setup

* An LDAP server whose password entries are using ldap format, eg. `{CRYPT}$6$…$…`. When the format is `{CRYPT}`, the string remainder should be parsed according to [this](https://en.wikipedia.org/wiki/Crypt_(C)).
* Some LDAP entries using the deprecated and insecure DES format, which is one of the formats supported by `crypt`.
* Try to log in with one of those accounts

# What should happen

The authentication should work.

# What happens

The authentication attempt results in Error 500

# Why does it happen

When trying to extract the hash salt within `utils.py` on such a format, the absence of `$` in the DES encoding makes it return an empty salt. This is interpreted later on as a missing salt, causing an exception because `{CRYPT}` requires a salt. Simply passing the whole hashed password to `crypt.crypt` solves the problem.

**Comment by nitmir** [comment]
Thank for contributing. I'll close that once the fix reach the master branch on the next (probably minor) release.
