### ISSUE TITLE
ImportError: The crypt module is not supported on Windows

### ISSUE THREAD

**Issue by saikrishnavadali05** [nitmir/django-cas-server#67]
When I run the server, I am getting this error. I am running the cas-server module on windows machine. Can you please solve this issue?

**Comment by nitmir** [comment]
Hi, sorry for the long response delay
I do not currently have the means nor the will to maintain a windows compatibility. If you absolutely must use windows, the easiest (en cleanest) workaround whould be to use WSL (available in windows 10 and 2019).
As a hot and dirty fix, you could create an empty file called `crypt.py` at the root of your django project. As long as you to not use any auth backend requiring crypt support, you should be ok.

If you have the time and skills to support Windows, pull requests are always welcome.
