### ISSUE TITLE
setup.py has wrong versions of Django in install_requires

### ISSUE THREAD

**Issue by KenWhitesell** [nitmir/django-cas-server#75]
The install_requires setting in setup.py has:
install_requires=[
            'Django >= 1.11,<3.2', 'requests >= 2.4', 'requests_futures >= 0.9.5',
            'lxml >= 3.4', 'six >= 1'
        ],
preventing it from installing cleanly via pip with Django 3.2

**Comment by KenWhitesell** [comment]
For clarification, this is from the version on pypi.org, not in the repo.

**Comment by nitmir** [comment]
Hi,
Thanks for reporting.
I have planed to release a patch release soon (maybe this weekend) to fix this.

**Comment by nitmir** [comment]
This is fixed in v1.3.1
