### ISSUE TITLE
Customisable Django Forms

### ISSUE THREAD

**Issue by Slixe** [nitmir/django-cas-server#88]
Hey there,
Thanks for your amazing project !
I would like to ask if you would be agree to use `utils.import_attr` and expose `USER_CREDENTIAL_FORM` (and others) to have dynamic choice of which form to use directly in `settings.py` ?

That would be a great feature and would prevent people like me to just overwrite it.

I can do a pull request if you're agree :)

**Comment by nitmir** [comment]
Hello,

Does 17c54aa1aff2d299bd2f1becea8084f8a87efed7 seems acceptable to you ?

Cheers

**Comment by Slixe** [comment]
hey there,

lgtm, thanks for your time ! :)
